# Generated by Django 6.1 on 2026-09-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
    ]
