# Generated by Django 6.1 on 2026-10-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_starred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='thumbnail',
            new_name='experience_image_url',
        ),
    ]
